server:
  port: 8888

spring:
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: reviews_route
          uri: http://localhost:6004
          predicates:
            - Path=/reviews
          filters:
            - RewritePath=/reviews, /fast/api/reviews