server:
  port: 8888

spring:
  application:
    name: 'boki-tistory-api-gateway'
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOriginPatterns:
#              - "*"
#            allowedMethods:
#              - "*"
#            allowedHeaders:
#              - "*"
#            allowCredentials: true
#            maxAge: 3600

      routes:
        - id: reviews_route
          uri: http://localhost:6004
          predicates:
            - Path=/reviews
          filters:
            - RewritePath=/reviews, /fast/api/reviews

boki:
  svc:
#    user: {}
#    review: {}
    book:
      base-url: 'localhost:5004'
      http-url: 'http://${boki.svc.book.base-url}'
      websocket-url: 'ws://${boki.svc.book.base-url}'
      api-key: 'boki'

logging:
  level:
    boki.tistory.springcloudgatewayjava.filter: DEBUG

